$(document).ready(function(){
	$(".header__burger").click(function(event){
		$(".header__list").toggleClass("active");
	})
	//$(".flower__btn").click(function(event){
		//$(".buy__title").toggleClass("active");
		//$(".flower__time").toggleClass("active");
		//$(".flower__title").toggleClass("active");
		//$(".flower__text").toggleClass("active");
		//$(".flower__btn").toggleClass("active");
		//$(".flower__img").toggleClass("active");
		//$(".flower__buy").toggleClass("active");
		//$(".flower__body").toggleClass("active");
	//})
	$(".btn_1").click(function(event){
		$(".body_1").toggleClass("active");
		$(".img_1").toggleClass("active");
		$(".buy_1").toggleClass("active");
	})
	$(".btn_2").click(function(event){
		$(".body_2").toggleClass("active");
		$(".img_2").toggleClass("active");
		$(".buy_2").toggleClass("active");
	})
	$(".btn_3").click(function(event){
		$(".body_3").toggleClass("active");
		$(".img_3").toggleClass("active");
		$(".buy_3").toggleClass("active");
	})
	$(".btn_4").click(function(event){
		$(".body_4").toggleClass("active");
		$(".img_4").toggleClass("active");
		$(".buy_4").toggleClass("active");
	})
	$(".btn_5").click(function(event){
		$(".body_5").toggleClass("active");
		$(".img_5").toggleClass("active");
		$(".buy_5").toggleClass("active");
	})
	$(".btn_6").click(function(event){
		$(".body_6").toggleClass("active");
		$(".img_6").toggleClass("active");
		$(".buy_6").toggleClass("active");
	})
	$(".btn_7").click(function(event){
		$(".body_7").toggleClass("active");
		$(".img_7").toggleClass("active");
		$(".buy_7").toggleClass("active");
	})
	$(".btn_8").click(function(event){
		$(".body_8").toggleClass("active");
		$(".img_8").toggleClass("active");
		$(".buy_8").toggleClass("active");
	})
	$(".btn_9").click(function(event){
		$(".body_9").toggleClass("active");
		$(".img_9").toggleClass("active");
		$(".buy_9").toggleClass("active");
	})
	$(".btn_10").click(function(event){
		$(".body_10").toggleClass("active");
		$(".img_10").toggleClass("active");
		$(".buy_10").toggleClass("active");
	})
	$(".btn_11").click(function(event){
		$(".body_11").toggleClass("active");
		$(".img_11").toggleClass("active");
		$(".buy_11").toggleClass("active");
	})
	$(".btn_12").click(function(event){
		$(".body_12").toggleClass("active");
		$(".img_12").toggleClass("active");
		$(".buy_12").toggleClass("active");
	})



	$(".del_1").click(function(event){
		$(".body_1").toggleClass("unactive");
		$(".img_1").toggleClass("unactive");
		$(".buy_1").toggleClass("unactive");
	})
	$(".del_2").click(function(event){
		$(".body_2").toggleClass("unactive");
		$(".img_2").toggleClass("unactive");
		$(".buy_2").toggleClass("unactive");
	})
	$(".del_3").click(function(event){
		$(".body_3").toggleClass("unactive");
		$(".img_3").toggleClass("unactive");
		$(".buy_3").toggleClass("unactive");
	})
	$(".del_4").click(function(event){
		$(".body_4").toggleClass("unactive");
		$(".img_4").toggleClass("unactive");
		$(".buy_4").toggleClass("unactive");
	})
	$(".del_5").click(function(event){
		$(".body_5").toggleClass("unactive");
		$(".img_5").toggleClass("unactive");
		$(".buy_5").toggleClass("unactive");
	})
	$(".del_6").click(function(event){
		$(".body_6").toggleClass("unactive");
		$(".img_6").toggleClass("unactive");
		$(".buy_6").toggleClass("unactive");
	})
	$(".del_7").click(function(event){
		$(".body_7").toggleClass("unactive");
		$(".img_7").toggleClass("unactive");
		$(".buy_7").toggleClass("unactive");
	})
	$(".del_8").click(function(event){
		$(".body_8").toggleClass("unactive");
		$(".img_8").toggleClass("unactive");
		$(".buy_8").toggleClass("unactive");
	})
	$(".del_9").click(function(event){
		$(".body_9").toggleClass("unactive");
		$(".img_9").toggleClass("unactive");
		$(".buy_9").toggleClass("unactive");
	})
	$(".del_10").click(function(event){
		$(".body_10").toggleClass("unactive");
		$(".img_10").toggleClass("unactive");
		$(".buy_10").toggleClass("unactive");
	})
	$(".del_11").click(function(event){
		$(".body_11").toggleClass("unactive");
		$(".img_11").toggleClass("unactive");
		$(".buy_11").toggleClass("unactive");
	})
	$(".del_12").click(function(event){
		$(".body_12").toggleClass("unactive");
		$(".img_12").toggleClass("unactive");
		$(".buy_12").toggleClass("unactive");
	})


	
})
